version: 2.1

orbs:
  python: circleci/python@1.5.0
  aws-cli: circleci/aws-cli@1.2.1

jobs:
  build-and-test:
    executor:
      name: python/default
      tag: '3.7'
    steps:
      - checkout
      - run:
          name: Create Virtual Environment
          command: |
            virtualenv -p python3.7 env
            echo "source ./env/Scripts/activate" >> $BASH_ENV
      - run:
          name: Installing Dependencies
          command: pip install -r requirements.txt
      - run:
          name: Testing
          command: pytest
      - run:
          name: Create Zip File archive of dependencies
          command: |
            cd env/lib/python3.7/site-packages
            zip -r9 ../../../../function.zip .
      - run:
          name: Add app to Zip File
          command: zip -g  ./function.zip app
      - persist_to_workspace:
          root: .
          paths:
            - function.zip

workflows:
  build-test-and-deploy:
    jobs:
      - build-and-test:
        filters:
          branches:
            only:
              - deployment